### PR TITLE
Fixing animations on master: Rotate, Fade, Zoom

### PR DESCRIPTION
**Pull request by Simbaclaws**
Dear @kolkov,

I have made a new pull request that can be merged with master in order to fix the other animations of the gallery.

Like previously discussed the transition animations should be separated in a separate file and the isAnimating and transition duration should be configurable.

These are things that still need to be done, but for now this pull request might be useful for fixing the other animations.

Thank you for taking the time to improve the gallery :+1: ,
Simbaclaws

### CODE REVIEW

**Comment by kolkov** [comment]
I think you need to squash some commits

**Comment by Simbaclaws** [comment]
I did git rebase -i HEAD~10

But this didn't squash all the commits in the pull request.
How can I squash all of the commits?

**Comment by kolkov** [comment]
I use SmartGit for my Git. It's free for opensource. https://www.syntevo.com/smartgit/

**Comment by Simbaclaws** [comment]
Dear @kolkov, I made a mistake in the last 2 commits trying to squash them together, is this now in master?

**Comment by kolkov** [comment]
Ok I fixed this squash artifacts. But image component still not working. Fix please in next PR.

**Pull request merged**
