### PR TITLE
Update ngx-gallery.module.ts

### PR DESCRIPTION
**Pull request by andrejm7**
Update for angular 13. Remove import brower

### CODE REVIEW

**Comment by kolkov** [comment]
Hi! What will it give us?

**Comment by andrejm7** [comment]
I removed the browseranimation import... where there is an error in angular 13... this import must be unique in app.module

there are more users requesting this.

**Comment by andrejm7** [comment]
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by kolkov** [comment]
Thanks for the PR! I think we need to add `@angular/animations` to `peerDependencies` of packaje.json in library folder in this PR.

**Comment by andrejm7** [comment]
thanks

**Pull request merged**
