### PR TITLE
Changed left positioning for images to translateX (update): added video support

### PR DESCRIPTION
**Pull request by Simbaclaws**
I created an update on how the animation for sliding works for images, this would make the image sliding hardware accelerated by using translateX instead of position left.

Please accept my pull request.

### CODE REVIEW

**Comment by Simbaclaws** [comment]
There is an issue with the build process from Tracis CI.

It's related to this:
https://github.com/ng-packagr/ng-packagr/issues/1592

Haven't found a solution yet.
It hasn't got anything to do with my code I suppose.

**Comment by kolkov** [comment]
Thanks! I will try to review this PR soon as possible.

**Comment by Simbaclaws** [comment]
Hey, I added support for video inside the master branch of my forked repo.
Please review the pull request as it should now be possible to add video files inside the image attributes.

**Comment by Simbaclaws** [comment]
Alright the build succeeded. I think it might've been linting issues that were causing the build not to complete.

I'm not sure about the codecov/patch and codecov/project though. Does code coverage make a difference?

**Comment by Simbaclaws** [comment]
After this pull request have been merged I'll try fixing 
https://github.com/kolkov/ngx-gallery/issues/4
which I have posted the theoretical solution to.

**Comment by kolkov** [comment]
Is it possible to fix tests coverage?

**Comment by kolkov** [comment]
Thanks! I check this soon as possible.

**Comment by Simbaclaws** [comment]
I'm not that familiar with test coverage, how would I fix those?
What would I need to do?

**Comment by Simbaclaws** [comment]
So in other words code coverage basically means code that hasn't yet had tests been written for right?

I'm new to this and would need to learn how to do this before actually writing code tests in angular.
Would love to find an in-depth tutorial on the subject matter somewhere.

**Comment by kolkov** [comment]
Thanks for the contributions.

**Comment by kolkov** [comment]
Update the documentation please.

**Comment by Simbaclaws** [comment]
Do you mean the README.md?
Or do you mean actual code documentation with code comments?

I can update README.md if that's what you're asking.

**Comment by Simbaclaws** [comment]
Or I could upload the README.md as README.txt in this conversation and all you'd have to do is change it back to md and upload it to your repository.

Would this documentation update suffice?
[README.txt](https://github.com/kolkov/ngx-gallery/files/4496798/README.txt)

**Pull request merged**
