### PR TITLE
Redo: fixing animations on master

### PR DESCRIPTION
**Pull request by Simbaclaws**
I reverted my master branch back to the commit that was working.

I couldn't squash the commits successfully so please accept this commit from master, everything is working in this branch.

Please review the changes if necessary.
The conflict might need to be fixed still.

So far everything seems to be working on my master branch, so I'm not sure if this conflict is necessary.

### CODE REVIEW

**Comment by kolkov** [comment]
A push one commit too )) please resolve conflicts.

**Comment by Simbaclaws** [comment]
Don't merge yet please, apparently this conflict seems to cause issues.

**Comment by kolkov** [comment]
Ok, I will waiting for...

**Comment by Simbaclaws** [comment]
I think this solves the issues, could you check to make sure?

**Comment by kolkov** [comment]
Ok. This fixed image component, but video still continue playing, if click play button in preview component and then closed. Fix this please.

**Comment by Simbaclaws** [comment]
Okay, now it would stop playing when closing the preview window.

**Comment by kolkov** [comment]
Thanks! Merged!

**Comment by Simbaclaws** [comment]
@kolkov 

I need this gallery for an app that I'm making, when can we expect the master branch to be up to date with the npm repository here: https://www.npmjs.com/package/@kolkov/ngx-gallery ?

The earlier this can be, the better it would be for me :+1:

**Comment by kolkov** [comment]
At the moment, I am consulting with my colleagues in a telegram which version should be issued, minor or major, taking into account the changes that we have made.

**Comment by Simbaclaws** [comment]
Thank you, please let me know when you have a response :)

**Comment by kolkov** [comment]
Try to use `npm link` to use library localy.

**Comment by Simbaclaws** [comment]
I'd rather wait until it is officially in the repository.
I'll make a new branch of my app tomorrow to test things locally with npm link.

**Comment by Simbaclaws** [comment]
@kolkov 

Do you perhaps know how I can use this github repository in my project using npm?
I'm not quite sure how I can get this to work in my project. I'd rather not create a symbolic link as that would only work on local development, I need these changes in production. What can I do to use the newest version of this library?

**Comment by kolkov** [comment]
This changes is not ready for production yet. Now I thinking about some changes that may cause some API change. If I make this changes I release new major version. What problem to use npm link for production?

**Comment by Simbaclaws** [comment]
The last error that I'm seeing is:

```
core.js:6237 ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.```

But I don't know how to solve it.

Basically I import ```CommonModule, BrowserModule, BrowserAnimationsModule```
inside of my app.module.ts

after I've build ngx-gallery with: ```npm run build:lib``` and went to the dist gallery folder to ```npm link``` and then to my project folder to ```npm link @kolkov/ngx-gallery```.

This would create a @kolkov/ngx-gallery folder inside of my node_modules folder, but I'm guessing some of the files inside of the ngx-gallery import either BrowserModule or BrowserAnimationsModule.

According to this stackoverflow answer:
https://stackoverflow.com/questions/45975675/lazy-loading-browsermodule-has-already-been-loaded

The modules should only be imported **once**.

How can I solve this issue?

**Comment by kolkov** [comment]
Need repo, to reproduce...

**Comment by Simbaclaws** [comment]
I'll try creating an example project later on, I can't give my current repo because it's private to our organisation.

I'll try creating a different solution by using a lightbox of some kind instead of a full gallery.

**Comment by Simbaclaws** [comment]
Hey kolkov,

Sorry for the late response, I have not looked at this in a long time.

Is there any progress on the new release?

What does still need to be done?
I haven't reproduced the issue in my project yet.

I would love to see this released, I'm just curious what you think should be done to make a new release, you said it wasn't ready because it needed API changes.

Which are those exactly?

**Comment by kolkov** [comment]
I think we need to rewrite this project with a slider component. And we need to move only one slider that contains all slides.

**Comment by Simbaclaws** [comment]
For me I'm not so sure whether I'd be able to contribute my time into making that happen, it would at least not be in the professional sense that the company I work for wants me to do this in their time. It would become a hobby project in that case.

In any case I don't know whether I want to spend so much time in developing something I can easily find an alternative for online. Since I can probably get another angular carousel from any other source, like for example this one:
https://mdbootstrap.com/docs/angular/advanced/carousel/

I understand you put a lot of effort and time in this project, and I appreciate it. But I just don't know whether I'll be either using it, or contributing further to it based on the time that I have.

**Pull request merged**
